development: &common
  adapter: mysql
  encoding: utf8
  database: laughtrack_development
  username: laughtrack
  password: 
  reconnect: false
  pool: 5

test:
  <<: *common
  database: laughtrack_test

production:
  <<: *common
  database: laughtrack_production
